name: test
on:
  push:
  pull_request:
jobs:
  powershell:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - shell: pwsh
        run: ./tests/run.ps1
